# Generated by Django 4.2.7 on 2025-08-25 03:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DashboardWidget",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="组件名称")),
                ("title", models.CharField(max_length=200, verbose_name="显示标题")),
                (
                    "widget_type",
                    models.CharField(
                        choices=[
                            ("chart", "图表"),
                            ("counter", "计数器"),
                            ("list", "列表"),
                            ("progress", "进度条"),
                            ("alert", "警告"),
                        ],
                        max_length=20,
                        verbose_name="组件类型",
                    ),
                ),
                (
                    "config",
                    models.TextField(
                        help_text="JSON格式的组件配置", verbose_name="配置信息"
                    ),
                ),
                ("position_x", models.IntegerField(default=0, verbose_name="X位置")),
                ("position_y", models.IntegerField(default=0, verbose_name="Y位置")),
                ("width", models.IntegerField(default=4, verbose_name="宽度")),
                ("height", models.IntegerField(default=3, verbose_name="高度")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="是否启用"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "仪表盘组件",
                "verbose_name_plural": "仪表盘组件",
                "db_table": "admin_dashboard_widget",
                "ordering": ["position_y", "position_x"],
            },
        ),
        migrations.CreateModel(
            name="SystemConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="配置名称"
                    ),
                ),
                (
                    "key",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="配置键"
                    ),
                ),
                ("value", models.TextField(verbose_name="配置值")),
                (
                    "config_type",
                    models.CharField(
                        choices=[
                            ("basic", "基本配置"),
                            ("security", "安全配置"),
                            ("notification", "通知配置"),
                            ("integration", "集成配置"),
                            ("performance", "性能配置"),
                        ],
                        default="basic",
                        max_length=20,
                        verbose_name="配置类型",
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="描述")),
                (
                    "is_encrypted",
                    models.BooleanField(default=False, verbose_name="是否加密"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="是否启用"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "系统配置",
                "verbose_name_plural": "系统配置",
                "db_table": "admin_system_config",
                "ordering": ["config_type", "name"],
            },
        ),
        migrations.CreateModel(
            name="Dictionary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[],
                        max_length=50,
                        verbose_name="字典分类",
                    ),
                ),
                ("key", models.CharField(max_length=100, verbose_name="字典键")),
                ("label", models.CharField(max_length=200, verbose_name="显示标签")),
                ("description", models.TextField(blank=True, verbose_name="描述")),
                (
                    "priority",
                    models.IntegerField(
                        default=0, help_text="数值越大优先级越高", verbose_name="优先级"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "启用"), ("inactive", "禁用")],
                        default="active",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "config",
                    models.TextField(
                        blank=True,
                        help_text="JSON格式的扩展配置",
                        verbose_name="配置信息",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "字典",
                "verbose_name_plural": "字典",
                "db_table": "admin_dictionary",
                "ordering": ["-priority", "key"],
                "indexes": [
                    models.Index(
                        fields=["category", "status"],
                        name="admin_dicti_categor_217c9b_idx",
                    ),
                    models.Index(
                        fields=["priority"], name="admin_dicti_priorit_9904d3_idx"
                    ),
                ],
                "unique_together": {("category", "key")},
            },
        ),
        migrations.CreateModel(
            name="AdminLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("create", "创建"),
                            ("update", "更新"),
                            ("delete", "删除"),
                            ("export", "导出"),
                            ("import", "导入"),
                            ("config", "配置"),
                            ("login", "登录"),
                            ("logout", "登出"),
                        ],
                        max_length=20,
                        verbose_name="操作类型",
                    ),
                ),
                (
                    "model_name",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="模型名称"
                    ),
                ),
                (
                    "object_id",
                    models.CharField(blank=True, max_length=100, verbose_name="对象ID"),
                ),
                ("description", models.TextField(verbose_name="操作描述")),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="IP地址"
                    ),
                ),
                ("user_agent", models.TextField(blank=True, verbose_name="用户代理")),
                (
                    "result",
                    models.CharField(
                        choices=[("success", "成功"), ("failed", "失败")],
                        default="success",
                        max_length=20,
                        verbose_name="操作结果",
                    ),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, verbose_name="错误信息"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="操作用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "管理日志",
                "verbose_name_plural": "管理日志",
                "db_table": "admin_log",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "created_at"],
                        name="admin_log_user_id_f8d8eb_idx",
                    ),
                    models.Index(
                        fields=["action", "created_at"],
                        name="admin_log_action_c41bf6_idx",
                    ),
                    models.Index(
                        fields=["model_name", "created_at"],
                        name="admin_log_model_n_274025_idx",
                    ),
                ],
            },
        ),
    ]
