# Generated by Django 4.2.7 on 2025-09-10 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dictionary',
            name='category',
            field=models.CharField(choices=[('user_category', '用户分类'), ('system_config', '系统配置'), ('asset_type', '资产类型'), ('asset_status', '资产状态'), ('software_type', '软件类型'), ('department', '部门'), ('status', '状态'), ('priority', '优先级'), ('environment', '环境')], max_length=50, verbose_name='字典分类'),
        ),
    ]
