# Generated by Django 4.2.7 on 2025-09-11 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_management', '0002_alter_dictionary_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dictionary',
            name='category',
            field=models.CharField(choices=[], max_length=50, verbose_name='字典分类'),
        ),
    ]
