# Generated by Django 4.2.7 on 2025-08-23 16:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "session_key",
                    models.CharField(
                        max_length=40, unique=True, verbose_name="会话密钥"
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(verbose_name="IP地址")),
                ("user_agent", models.TextField(blank=True, verbose_name="用户代理")),
                (
                    "device_info",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="设备信息"
                    ),
                ),
                (
                    "login_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="登录时间"),
                ),
                (
                    "last_activity",
                    models.DateTimeField(auto_now=True, verbose_name="最后活动时间"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="是否活跃"),
                ),
                (
                    "logout_reason",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("normal", "正常登出"),
                            ("kicked", "被管理员踢出"),
                            ("timeout", "会话超时"),
                            ("force", "强制登出"),
                        ],
                        max_length=50,
                        verbose_name="登出原因",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "用户会话",
                "verbose_name_plural": "用户会话",
                "db_table": "user_session",
                "ordering": ["-last_activity"],
                "indexes": [
                    models.Index(
                        fields=["user", "is_active"],
                        name="user_sessio_user_id_4f7411_idx",
                    ),
                    models.Index(
                        fields=["session_key"], name="user_sessio_session_ab559f_idx"
                    ),
                    models.Index(
                        fields=["last_activity"], name="user_sessio_last_ac_e10a79_idx"
                    ),
                ],
            },
        ),
    ]
