# Generated by Django 4.2.7 on 2025-08-23 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_usersession"),
    ]

    operations = [
        migrations.AddField(
            model_name="usersession",
            name="has_websocket",
            field=models.BooleanField(
                default=False, verbose_name="是否有WebSocket连接"
            ),
        ),
        migrations.AddField(
            model_name="usersession",
            name="websocket_channels",
            field=models.JSONField(
                blank=True, default=list, verbose_name="WebSocket通道"
            ),
        ),
    ]
