# Generated by Django 4.2.7 on 2025-08-24 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_alter_usersession_logout_reason"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usersession",
            name="logout_reason",
            field=models.CharField(
                blank=True,
                choices=[
                    ("normal", "正常登出"),
                    ("kicked", "被管理员踢出"),
                    ("timeout", "会话超时"),
                    ("force", "强制登出"),
                    ("replaced", "被新会话替换"),
                    ("limit_exceeded", "超出会话限制"),
                    ("admin_clear", "管理员清理"),
                ],
                max_length=50,
                verbose_name="登出原因",
            ),
        ),
    ]
