# Generated by Django 4.2.7 on 2025-08-25 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_alter_usersession_logout_reason"),
    ]

    operations = [
        migrations.CreateModel(
            name="Dictionary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("user_category", "用户分类"),
                            ("system_config", "系统配置"),
                            ("asset_type", "资产类型"),
                            ("department", "部门"),
                            ("status", "状态"),
                        ],
                        max_length=50,
                        verbose_name="字典分类",
                    ),
                ),
                ("key", models.CharField(max_length=100, verbose_name="字典键")),
                ("label", models.CharField(max_length=200, verbose_name="显示标签")),
                ("description", models.TextField(blank=True, verbose_name="描述")),
                (
                    "priority",
                    models.IntegerField(
                        default=0, help_text="数值越大优先级越高", verbose_name="优先级"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "启用"), ("inactive", "禁用")],
                        default="active",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "config",
                    models.TextField(
                        blank=True,
                        help_text="JSON格式的扩展配置",
                        verbose_name="配置信息",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "字典",
                "verbose_name_plural": "字典",
                "db_table": "dictionary",
                "ordering": ["-priority", "key"],
                "indexes": [
                    models.Index(
                        fields=["category", "status"],
                        name="dictionary_categor_043d0d_idx",
                    ),
                    models.Index(
                        fields=["priority"], name="dictionary_priorit_c4ebce_idx"
                    ),
                ],
                "unique_together": {("category", "key")},
            },
        ),
    ]
