# Generated by Django 4.2.7 on 2025-08-25 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_dictionary"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Dictionary",
        ),
    ]
