# Generated by Django 4.2.7 on 2025-08-24 11:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ScanTask",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "task_name",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="任务名称"
                    ),
                ),
                ("ip_ranges", models.JSONField(verbose_name="IP范围列表")),
                (
                    "check_type",
                    models.IntegerField(
                        choices=[
                            (0, "SSH"),
                            (1, "LDAP"),
                            (2, "SMTP"),
                            (3, "FTP"),
                            (4, "HTTP"),
                            (5, "POP"),
                            (6, "NNTP"),
                            (7, "IMAP"),
                            (8, "TCP"),
                            (9, "Zabbix agent"),
                            (10, "SNMPv1 agent"),
                            (11, "SNMPv2 agent"),
                            (12, "ICMP ping"),
                            (13, "SNMPv3 agent"),
                            (14, "HTTPS"),
                            (15, "Telnet"),
                        ],
                        verbose_name="检查类型",
                    ),
                ),
                (
                    "ports",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="端口范围"
                    ),
                ),
                (
                    "key",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="检查键值/SNMP OID",
                    ),
                ),
                (
                    "snmp_community",
                    models.CharField(
                        blank=True,
                        default="public",
                        max_length=255,
                        null=True,
                        verbose_name="SNMP社区",
                    ),
                ),
                (
                    "snmpv3_config",
                    models.JSONField(blank=True, null=True, verbose_name="SNMPv3配置"),
                ),
                (
                    "unique_check",
                    models.IntegerField(default=0, verbose_name="唯一性检查"),
                ),
                (
                    "host_source",
                    models.IntegerField(default=1, verbose_name="主机名称来源"),
                ),
                (
                    "name_source",
                    models.IntegerField(default=0, verbose_name="可见名称来源"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "等待中"),
                            ("running", "运行中"),
                            ("completed", "已完成"),
                            ("failed", "失败"),
                            ("cancelled", "已取消"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="任务状态",
                    ),
                ),
                ("progress", models.IntegerField(default=0, verbose_name="进度百分比")),
                (
                    "result_data",
                    models.JSONField(
                        blank=True, null=True, verbose_name="扫描结果数据"
                    ),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, null=True, verbose_name="错误信息"),
                ),
                (
                    "zabbix_drule_id",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Zabbix发现规则ID",
                    ),
                ),
                (
                    "zabbix_task_id",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Zabbix任务ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="开始时间"
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="完成时间"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建者",
                    ),
                ),
            ],
            options={
                "verbose_name": "扫描任务",
                "verbose_name_plural": "扫描任务",
                "db_table": "scan_tasks",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="IPRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(unique=True, verbose_name="IP地址"),
                ),
                (
                    "hostname",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="主机名"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "在用"),
                            ("available", "可用"),
                            ("reserved", "预留"),
                            ("conflict", "冲突"),
                        ],
                        default="available",
                        max_length=20,
                        verbose_name="IP状态",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("static", "静态IP"),
                            ("dynamic", "动态IP"),
                            ("gateway", "网关"),
                            ("dns", "DNS服务器"),
                        ],
                        default="static",
                        max_length=20,
                        verbose_name="IP类型",
                    ),
                ),
                (
                    "mac_address",
                    models.CharField(
                        blank=True, max_length=17, null=True, verbose_name="MAC地址"
                    ),
                ),
                (
                    "device",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="关联设备"
                    ),
                ),
                (
                    "subnet",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="所属网段"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="备注"),
                ),
                (
                    "ping_status",
                    models.CharField(
                        choices=[("online", "在线"), ("offline", "离线")],
                        default="offline",
                        max_length=20,
                        verbose_name="Ping状态",
                    ),
                ),
                (
                    "last_seen",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="最后在线时间"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建者",
                    ),
                ),
            ],
            options={
                "verbose_name": "IP记录",
                "verbose_name_plural": "IP记录",
                "db_table": "ip_records",
                "ordering": ["ip_address"],
            },
        ),
        migrations.CreateModel(
            name="ScanResult",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(verbose_name="IP地址")),
                (
                    "hostname",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="主机名"
                    ),
                ),
                (
                    "mac_address",
                    models.CharField(
                        blank=True, max_length=17, null=True, verbose_name="MAC地址"
                    ),
                ),
                ("status", models.CharField(max_length=20, verbose_name="检查状态")),
                (
                    "response_time",
                    models.FloatField(
                        blank=True, null=True, verbose_name="响应时间(ms)"
                    ),
                ),
                (
                    "service_info",
                    models.JSONField(blank=True, null=True, verbose_name="服务信息"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="发现时间"),
                ),
                (
                    "scan_task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="results",
                        to="ip_management.scantask",
                        verbose_name="扫描任务",
                    ),
                ),
            ],
            options={
                "verbose_name": "扫描结果",
                "verbose_name_plural": "扫描结果",
                "db_table": "scan_results",
                "ordering": ["ip_address"],
                "unique_together": {("scan_task", "ip_address")},
            },
        ),
    ]
