# Generated by Django 4.2.7 on 2025-08-26 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ip_management", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="iprecord",
            name="is_auto_discovered",
            field=models.BooleanField(
                default=False,
                help_text="标识此IP是否由Zabbix自动发现",
                verbose_name="自动发现",
            ),
        ),
        migrations.AddField(
            model_name="iprecord",
            name="zabbix_drule_id",
            field=models.CharField(
                blank=True,
                help_text="关联的Zabbix发现规则ID",
                max_length=50,
                null=True,
                verbose_name="Zabbix发现规则ID",
            ),
        ),
    ]
