# Generated by Django 4.2.7 on 2025-08-26 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ip_management", "0002_iprecord_is_auto_discovered_iprecord_zabbix_drule_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="iprecord",
            name="monitoring_enabled",
            field=models.BooleanField(
                default=True, help_text="是否启用对此IP的监控", verbose_name="启用监控"
            ),
        ),
    ]
