# Generated by Django 4.2.7 on 2025-08-26 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ip_management", "0002_add_monitoring_enabled"),
        ("ip_management", "0003_iprecord_monitoring_enabled"),
    ]

    operations = []
