# Generated by Django 4.2.7 on 2025-08-30 13:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='部门名称')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='部门编码')),
                ('description', models.TextField(blank=True, null=True, verbose_name='部门描述')),
                ('level', models.IntegerField(default=1, verbose_name='部门层级')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序')),
                ('status', models.CharField(choices=[('active', '正常'), ('inactive', '停用')], default='active', max_length=20, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_departments', to=settings.AUTH_USER_MODEL, verbose_name='部门负责人')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='organization.department', verbose_name='上级部门')),
            ],
            options={
                'verbose_name': '部门',
                'verbose_name_plural': '部门',
                'ordering': ['level', 'sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='职位名称')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='职位编码')),
                ('level', models.CharField(choices=[('junior', '初级'), ('intermediate', '中级'), ('senior', '高级'), ('expert', '专家'), ('manager', '管理'), ('director', '总监'), ('vp', '副总'), ('ceo', '总裁')], default='junior', max_length=20, verbose_name='职位级别')),
                ('description', models.TextField(blank=True, null=True, verbose_name='职位描述')),
                ('responsibilities', models.TextField(blank=True, null=True, verbose_name='岗位职责')),
                ('requirements', models.TextField(blank=True, null=True, verbose_name='任职要求')),
                ('salary_range_min', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='薪资范围最低')),
                ('salary_range_max', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='薪资范围最高')),
                ('status', models.CharField(choices=[('active', '正常'), ('inactive', '停用')], default='active', max_length=20, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='organization.department', verbose_name='所属部门')),
            ],
            options={
                'verbose_name': '职位',
                'verbose_name_plural': '职位',
                'ordering': ['department', 'level', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(max_length=50, unique=True, verbose_name='工号')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='联系电话')),
                ('mobile', models.CharField(blank=True, max_length=20, null=True, verbose_name='手机号码')),
                ('office_location', models.CharField(blank=True, max_length=200, null=True, verbose_name='办公地点')),
                ('hire_date', models.DateField(verbose_name='入职日期')),
                ('probation_end_date', models.DateField(blank=True, null=True, verbose_name='试用期结束日期')),
                ('contract_type', models.CharField(choices=[('full_time', '全职'), ('part_time', '兼职'), ('contract', '合同工'), ('intern', '实习生')], default='full_time', max_length=20, verbose_name='合同类型')),
                ('employment_status', models.CharField(choices=[('active', '在职'), ('probation', '试用期'), ('leave', '请假'), ('resigned', '离职'), ('terminated', '解雇')], default='probation', max_length=20, verbose_name='就业状态')),
                ('emergency_contact_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='紧急联系人')),
                ('emergency_contact_phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='紧急联系电话')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='organization.department', verbose_name='所属部门')),
                ('direct_supervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subordinates', to='organization.employee', verbose_name='直接上级')),
                ('position', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='organization.position', verbose_name='职位')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employee_profile', to=settings.AUTH_USER_MODEL, verbose_name='关联用户')),
            ],
            options={
                'verbose_name': '员工',
                'verbose_name_plural': '员工',
                'ordering': ['department', 'position', 'employee_id'],
            },
        ),
    ]
