# Generated by Django 4.2.7 on 2025-08-30 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_alter_employee_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='name',
            field=models.CharField(default='未命名员工', max_length=100, verbose_name='员工姓名'),
        ),
    ]
