# Generated by Django 4.2.7 on 2025-08-30 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0004_alter_employee_hire_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='salary',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='薪资'),
        ),
        migrations.AddField(
            model_name='employee',
            name='sort_order',
            field=models.IntegerField(default=0, verbose_name='排序'),
        ),
    ]
