# Generated by Django 4.2.7 on 2025-08-30 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0005_employee_salary_employee_sort_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='邮箱地址'),
        ),
    ]
