# Generated by Django 4.2.7 on 2025-08-23 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Asset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="资产名称")),
                (
                    "asset_type",
                    models.CharField(
                        choices=[
                            ("server", "服务器"),
                            ("network", "网络设备"),
                            ("storage", "存储设备"),
                            ("security", "安全设备"),
                            ("other", "其他设备"),
                        ],
                        max_length=20,
                        verbose_name="资产类型",
                    ),
                ),
                (
                    "serial_number",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="序列号"
                    ),
                ),
                (
                    "manufacturer",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="制造商"
                    ),
                ),
                (
                    "model",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="型号"
                    ),
                ),
                (
                    "purchase_date",
                    models.DateField(blank=True, null=True, verbose_name="购买日期"),
                ),
                (
                    "warranty_period",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="保修期限(月)"
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="价格",
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="存放位置"
                    ),
                ),
                (
                    "owner",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="负责人"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="资产描述"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "资产",
                "verbose_name_plural": "资产",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AssetCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="分类名称"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="分类描述"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "资产分类",
                "verbose_name_plural": "资产分类",
            },
        ),
        migrations.CreateModel(
            name="AssetStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="状态名称"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="状态描述"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "资产状态",
                "verbose_name_plural": "资产状态",
            },
        ),
        migrations.CreateModel(
            name="Server",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "server_type",
                    models.CharField(
                        choices=[
                            ("physical", "物理服务器"),
                            ("virtual", "虚拟服务器"),
                            ("cloud", "云服务器"),
                        ],
                        max_length=20,
                        verbose_name="服务器类型",
                    ),
                ),
                ("hostname", models.CharField(max_length=200, verbose_name="主机名")),
                ("ip_address", models.GenericIPAddressField(verbose_name="IP地址")),
                ("os", models.CharField(max_length=100, verbose_name="操作系统")),
                (
                    "os_version",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="操作系统版本",
                    ),
                ),
                ("cpu", models.CharField(max_length=100, verbose_name="CPU")),
                ("memory", models.IntegerField(verbose_name="内存(GB)")),
                ("disk", models.IntegerField(verbose_name="磁盘(GB)")),
                (
                    "kernel_version",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="内核版本"
                    ),
                ),
                ("ssh_port", models.IntegerField(default=22, verbose_name="SSH端口")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="是否激活"),
                ),
                (
                    "asset",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="server",
                        to="assets.asset",
                        verbose_name="关联资产",
                    ),
                ),
            ],
            options={
                "verbose_name": "服务器",
                "verbose_name_plural": "服务器",
            },
        ),
        migrations.CreateModel(
            name="NetworkDevice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "device_type",
                    models.CharField(
                        choices=[
                            ("router", "路由器"),
                            ("switch", "交换机"),
                            ("firewall", "防火墙"),
                            ("load_balancer", "负载均衡器"),
                            ("access_point", "无线接入点"),
                        ],
                        max_length=20,
                        verbose_name="设备类型",
                    ),
                ),
                ("hostname", models.CharField(max_length=200, verbose_name="主机名")),
                ("ip_address", models.GenericIPAddressField(verbose_name="IP地址")),
                (
                    "firmware_version",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="固件版本"
                    ),
                ),
                (
                    "port_count",
                    models.IntegerField(blank=True, null=True, verbose_name="端口数量"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="是否激活"),
                ),
                (
                    "asset",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="network_device",
                        to="assets.asset",
                        verbose_name="关联资产",
                    ),
                ),
            ],
            options={
                "verbose_name": "网络设备",
                "verbose_name_plural": "网络设备",
            },
        ),
        migrations.AddField(
            model_name="asset",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="assets.assetcategory",
                verbose_name="资产分类",
            ),
        ),
        migrations.AddField(
            model_name="asset",
            name="status",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="assets.assetstatus",
                verbose_name="资产状态",
            ),
        ),
    ]
