# Generated by Django 4.2.7 on 2025-08-28 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assets", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ZabbixTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "templateid",
                    models.CharField(max_length=50, unique=True, verbose_name="模板ID"),
                ),
                ("name", models.CharField(max_length=255, verbose_name="模板名称")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="模板描述"),
                ),
                (
                    "items_count",
                    models.IntegerField(default=0, verbose_name="监控项数量"),
                ),
                (
                    "triggers_count",
                    models.IntegerField(default=0, verbose_name="触发器数量"),
                ),
                ("macros_count", models.IntegerField(default=0, verbose_name="宏数量")),
                (
                    "icon",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="图标"
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="分类"
                    ),
                ),
                (
                    "groups",
                    models.JSONField(blank=True, default=list, verbose_name="主机组"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "Zabbix模板",
                "verbose_name_plural": "Zabbix模板",
                "ordering": ["name"],
            },
        ),
    ]
