# Generated by Django 4.2.7 on 2025-09-10 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_zabbixtemplate'),
    ]

    operations = [
        migrations.CreateModel(
            name='HardwareAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_tag', models.CharField(max_length=100, unique=True, verbose_name='资产标签')),
                ('model', models.CharField(max_length=200, verbose_name='型号')),
                ('asset_owner', models.CharField(max_length=100, verbose_name='资产责任人')),
                ('supplier_contact', models.CharField(blank=True, max_length=100, null=True, verbose_name='供应商联系人')),
                ('purchase_date', models.DateField(verbose_name='采购日期')),
                ('project_source', models.CharField(blank=True, max_length=200, null=True, verbose_name='项目来源')),
                ('asset_status', models.CharField(choices=[('in_use', '在用'), ('scrapped', '报废')], default='in_use', max_length=20, verbose_name='资产状态')),
                ('manufacturer', models.CharField(max_length=200, verbose_name='制造商')),
                ('specifications', models.JSONField(blank=True, default=dict, verbose_name='规格参数')),
                ('serial_number', models.CharField(max_length=200, unique=True, verbose_name='序列号')),
                ('room', models.CharField(blank=True, max_length=100, null=True, verbose_name='机房')),
                ('cabinet', models.CharField(blank=True, max_length=100, null=True, verbose_name='机柜')),
                ('u_position', models.CharField(blank=True, max_length=20, null=True, verbose_name='U位')),
                ('dimensions', models.CharField(blank=True, max_length=200, null=True, verbose_name='产品尺寸')),
                ('warranty_type', models.CharField(choices=[('original', '原厂保修'), ('third_party', '第三方保修')], max_length=20, verbose_name='保修类型')),
                ('warranty_start_date', models.DateField(verbose_name='保修开始日期')),
                ('warranty_end_date', models.DateField(verbose_name='保修结束日期')),
                ('monitoring_status', models.BooleanField(default=False, verbose_name='监控状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '硬件设施',
                'verbose_name_plural': '硬件设施',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='供应商名称')),
                ('contact_person', models.CharField(blank=True, max_length=100, null=True, verbose_name='联系人')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='联系电话')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='邮箱')),
                ('address', models.TextField(blank=True, null=True, verbose_name='地址')),
                ('description', models.TextField(blank=True, null=True, verbose_name='描述')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '供应商',
                'verbose_name_plural': '供应商',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='WarrantyUpdateRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_warranty_type', models.CharField(max_length=20, verbose_name='更新前保修类型')),
                ('new_warranty_type', models.CharField(max_length=20, verbose_name='更新后保修类型')),
                ('old_warranty_start_date', models.DateField(verbose_name='更新前保修开始日期')),
                ('new_warranty_start_date', models.DateField(verbose_name='更新后保修开始日期')),
                ('old_warranty_end_date', models.DateField(verbose_name='更新前保修结束日期')),
                ('new_warranty_end_date', models.DateField(verbose_name='更新后保修结束日期')),
                ('update_time', models.DateTimeField(auto_now_add=True, verbose_name='更新时间')),
                ('updated_by', models.CharField(blank=True, max_length=100, null=True, verbose_name='更新人')),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('hardware_asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warranty_updates', to='assets.hardwareasset', verbose_name='硬件资产')),
            ],
            options={
                'verbose_name': '保修更新记录',
                'verbose_name_plural': '保修更新记录',
                'ordering': ['-update_time'],
            },
        ),
        migrations.CreateModel(
            name='SpecificationUpdateRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_specifications', models.JSONField(default=dict, verbose_name='更新前规格参数')),
                ('new_specifications', models.JSONField(default=dict, verbose_name='更新后规格参数')),
                ('update_method', models.CharField(choices=[('manual', '手动'), ('automatic', '自动')], max_length=20, verbose_name='更新方式')),
                ('update_time', models.DateTimeField(auto_now_add=True, verbose_name='更新时间')),
                ('updated_by', models.CharField(blank=True, max_length=100, null=True, verbose_name='更新人')),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('hardware_asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spec_updates', to='assets.hardwareasset', verbose_name='硬件资产')),
            ],
            options={
                'verbose_name': '规格参数更新记录',
                'verbose_name_plural': '规格参数更新记录',
                'ordering': ['-update_time'],
            },
        ),
        migrations.AddField(
            model_name='hardwareasset',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='assets.supplier', verbose_name='供应商'),
        ),
    ]
