# Generated by Django 4.2.7 on 2025-09-10 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_hardwareasset_supplier_warrantyupdaterecord_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SoftwareAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='软件名称')),
                ('version', models.CharField(max_length=100, verbose_name='版本号')),
                ('software_type', models.CharField(choices=[('os', '操作系统'), ('database', '数据库'), ('middleware', '中间件'), ('application', '应用软件'), ('security', '安全软件'), ('monitoring', '监控软件'), ('other', '其他软件')], max_length=20, verbose_name='软件类型')),
                ('vendor', models.CharField(max_length=200, verbose_name='厂商')),
                ('description', models.TextField(blank=True, null=True, verbose_name='软件描述')),
                ('license_type', models.CharField(choices=[('commercial', '商业许可'), ('open_source', '开源许可'), ('free', '免费许可'), ('trial', '试用许可')], max_length=20, verbose_name='许可证类型')),
                ('license_key', models.TextField(blank=True, null=True, verbose_name='许可证密钥')),
                ('license_count', models.IntegerField(default=1, verbose_name='许可证数量')),
                ('license_start_date', models.DateField(blank=True, null=True, verbose_name='许可证开始日期')),
                ('license_end_date', models.DateField(blank=True, null=True, verbose_name='许可证结束日期')),
                ('purchase_date', models.DateField(blank=True, null=True, verbose_name='采购日期')),
                ('purchase_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='采购价格')),
                ('status', models.CharField(choices=[('active', '使用中'), ('inactive', '未使用'), ('expired', '已过期'), ('deprecated', '已弃用')], default='active', max_length=20, verbose_name='状态')),
                ('installation_path', models.CharField(blank=True, max_length=500, null=True, verbose_name='安装路径')),
                ('configuration', models.JSONField(blank=True, default=dict, verbose_name='配置信息')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('hardware_assets', models.ManyToManyField(blank=True, to='assets.hardwareasset', verbose_name='关联硬件资产')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='assets.supplier', verbose_name='供应商')),
            ],
            options={
                'verbose_name': '软件资产',
                'verbose_name_plural': '软件资产',
                'ordering': ['-created_at'],
                'unique_together': {('name', 'version')},
            },
        ),
    ]
