# Generated by Django 4.2.7 on 2025-09-10 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0004_softwareasset'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='softwareasset',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='softwareasset',
            name='asset_owner',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='资产责任人'),
        ),
        migrations.AddField(
            model_name='softwareasset',
            name='asset_status',
            field=models.CharField(choices=[('in_use', '在用'), ('deprecated', '已弃用'), ('testing', '测试中'), ('retired', '已退役')], default='in_use', max_length=20, verbose_name='资产状态'),
        ),
        migrations.AddField(
            model_name='softwareasset',
            name='asset_tag',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='资产标签'),
        ),
        migrations.AddField(
            model_name='softwareasset',
            name='dependencies',
            field=models.TextField(blank=True, null=True, verbose_name='依赖关系'),
        ),
        migrations.AddField(
            model_name='softwareasset',
            name='deployment_servers',
            field=models.TextField(blank=True, null=True, verbose_name='部署服务器'),
        ),
        migrations.AddField(
            model_name='softwareasset',
            name='last_update_date',
            field=models.DateField(blank=True, null=True, verbose_name='最后更新日期'),
        ),
        migrations.AddField(
            model_name='softwareasset',
            name='license_status',
            field=models.CharField(choices=[('active', '有效'), ('expired', '已过期'), ('suspended', '已暂停'), ('terminated', '已终止')], default='active', max_length=20, verbose_name='许可证状态'),
        ),
        migrations.AddField(
            model_name='softwareasset',
            name='license_used',
            field=models.IntegerField(default=0, verbose_name='已使用许可证'),
        ),
        migrations.AddField(
            model_name='softwareasset',
            name='minimum_requirements',
            field=models.JSONField(blank=True, default=dict, verbose_name='最低系统要求'),
        ),
        migrations.AddField(
            model_name='softwareasset',
            name='project_source',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='项目来源'),
        ),
        migrations.AddField(
            model_name='softwareasset',
            name='supplier_contact',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='供应商联系人'),
        ),
        migrations.AddField(
            model_name='softwareasset',
            name='support_end_date',
            field=models.DateField(blank=True, null=True, verbose_name='支持结束日期'),
        ),
        migrations.AddField(
            model_name='softwareasset',
            name='supported_os',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='支持的操作系统'),
        ),
        migrations.AddField(
            model_name='softwareasset',
            name='update_frequency',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='更新频率'),
        ),
        migrations.AddField(
            model_name='softwareasset',
            name='usage_description',
            field=models.TextField(blank=True, null=True, verbose_name='使用说明'),
        ),
        migrations.AlterField(
            model_name='softwareasset',
            name='license_type',
            field=models.CharField(choices=[('commercial', '商业许可'), ('open_source', '开源许可'), ('trial', '试用许可'), ('educational', '教育许可'), ('oem', 'OEM许可')], max_length=20, verbose_name='许可证类型'),
        ),
        migrations.AlterField(
            model_name='softwareasset',
            name='software_type',
            field=models.CharField(choices=[('operating_system', '操作系统'), ('database', '数据库'), ('middleware', '中间件'), ('application', '应用软件'), ('development_tool', '开发工具'), ('security_software', '安全软件'), ('monitoring_tool', '监控工具'), ('backup_software', '备份软件'), ('other', '其他软件')], max_length=30, verbose_name='软件类型'),
        ),
        migrations.AlterField(
            model_name='softwareasset',
            name='vendor',
            field=models.CharField(max_length=200, verbose_name='软件厂商'),
        ),
        migrations.AlterField(
            model_name='softwareasset',
            name='version',
            field=models.CharField(max_length=100, verbose_name='软件版本'),
        ),
        migrations.CreateModel(
            name='SoftwareVersionUpdateRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_version', models.CharField(max_length=100, verbose_name='更新前版本')),
                ('new_version', models.CharField(max_length=100, verbose_name='更新后版本')),
                ('update_method', models.CharField(choices=[('manual', '手动更新'), ('automatic', '自动更新'), ('scheduled', '计划更新')], max_length=20, verbose_name='更新方式')),
                ('update_time', models.DateTimeField(auto_now_add=True, verbose_name='更新时间')),
                ('updated_by', models.CharField(blank=True, max_length=100, null=True, verbose_name='更新人')),
                ('update_notes', models.TextField(blank=True, null=True, verbose_name='更新说明')),
                ('rollback_available', models.BooleanField(default=True, verbose_name='是否可回滚')),
                ('software_asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='version_updates', to='assets.softwareasset', verbose_name='软件资产')),
            ],
            options={
                'verbose_name': '软件版本更新记录',
                'verbose_name_plural': '软件版本更新记录',
                'ordering': ['-update_time'],
            },
        ),
        migrations.CreateModel(
            name='SoftwareLicenseUpdateRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_type', models.CharField(choices=[('renewal', '续费'), ('upgrade', '升级'), ('downgrade', '降级'), ('transfer', '转移'), ('termination', '终止')], max_length=20, verbose_name='更新类型')),
                ('old_license_type', models.CharField(max_length=20, verbose_name='更新前许可证类型')),
                ('old_license_count', models.IntegerField(verbose_name='更新前许可证数量')),
                ('old_license_start_date', models.DateField(blank=True, null=True, verbose_name='更新前开始日期')),
                ('old_license_end_date', models.DateField(blank=True, null=True, verbose_name='更新前结束日期')),
                ('new_license_type', models.CharField(max_length=20, verbose_name='更新后许可证类型')),
                ('new_license_count', models.IntegerField(verbose_name='更新后许可证数量')),
                ('new_license_start_date', models.DateField(blank=True, null=True, verbose_name='更新后开始日期')),
                ('new_license_end_date', models.DateField(blank=True, null=True, verbose_name='更新后结束日期')),
                ('update_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='更新费用')),
                ('update_time', models.DateTimeField(auto_now_add=True, verbose_name='更新时间')),
                ('updated_by', models.CharField(blank=True, max_length=100, null=True, verbose_name='更新人')),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('software_asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='license_updates', to='assets.softwareasset', verbose_name='软件资产')),
            ],
            options={
                'verbose_name': '软件许可证更新记录',
                'verbose_name_plural': '软件许可证更新记录',
                'ordering': ['-update_time'],
            },
        ),
        migrations.RemoveField(
            model_name='softwareasset',
            name='description',
        ),
        migrations.RemoveField(
            model_name='softwareasset',
            name='hardware_assets',
        ),
        migrations.RemoveField(
            model_name='softwareasset',
            name='status',
        ),
        migrations.CreateModel(
            name='SoftwareDeployment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server_hostname', models.CharField(max_length=200, verbose_name='服务器主机名')),
                ('server_ip', models.GenericIPAddressField(verbose_name='服务器IP')),
                ('deployment_path', models.CharField(max_length=500, verbose_name='部署路径')),
                ('deployment_status', models.CharField(choices=[('deployed', '已部署'), ('undeployed', '已卸载'), ('failed', '部署失败'), ('pending', '待部署')], max_length=20, verbose_name='部署状态')),
                ('deployment_date', models.DateTimeField(verbose_name='部署时间')),
                ('deployed_by', models.CharField(max_length=100, verbose_name='部署人')),
                ('configuration_details', models.JSONField(blank=True, default=dict, verbose_name='配置详情')),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('software_asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deployments', to='assets.softwareasset', verbose_name='软件资产')),
            ],
            options={
                'verbose_name': '软件部署记录',
                'verbose_name_plural': '软件部署记录',
                'ordering': ['-deployment_date'],
                'unique_together': {('software_asset', 'server_hostname')},
            },
        ),
    ]
