# Generated by Django 4.2.7 on 2025-09-13 02:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0006_alter_hardwareasset_asset_owner'),
    ]

    operations = [
    ]
