# Generated by Django 4.2.7 on 2025-09-13 02:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0007_auto_20250913_1038'),
    ]

    operations = [
    ]
