# Generated by Django 4.2.7 on 2025-09-13 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0009_auto_20250913_1044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hardwareasset',
            name='asset_owner',
            field=models.IntegerField(default=0, verbose_name='责任人id'),
        ),
    ]
