# Generated by Django 4.2.7 on 2025-09-15 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0010_alter_hardwareasset_asset_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hardwareasset',
            name='asset_owner',
            field=models.CharField(max_length=100, verbose_name='资产责任人'),
        ),
        migrations.AlterField(
            model_name='softwareasset',
            name='asset_owner',
            field=models.CharField(blank=True, max_length=100, verbose_name='资产责任人'),
        ),
        migrations.AlterField(
            model_name='softwareasset',
            name='asset_tag',
            field=models.CharField(blank=True, max_length=100, unique=True, verbose_name='资产标签'),
        ),
        migrations.AlterField(
            model_name='softwareasset',
            name='license_type',
            field=models.CharField(blank=True, choices=[('commercial', '商业许可'), ('open_source', '开源许可'), ('trial', '试用许可'), ('educational', '教育许可'), ('oem', 'OEM许可')], max_length=20, null=True, verbose_name='许可证类型'),
        ),
        migrations.AlterField(
            model_name='softwareasset',
            name='software_type',
            field=models.CharField(choices=[('operating_system', '操作系统'), ('database', '数据库'), ('middleware', '中间件'), ('application', '应用软件'), ('development_tool', '开发工具'), ('security_software', '安全软件'), ('monitoring_tool', '监控工具'), ('backup_software', '备份软件'), ('other', '其他软件')], default='other', max_length=30, null=True, verbose_name='软件类型'),
        ),
        migrations.AlterField(
            model_name='softwareasset',
            name='vendor',
            field=models.CharField(max_length=200, null=True, verbose_name='软件厂商'),
        ),
        migrations.AlterField(
            model_name='softwareasset',
            name='version',
            field=models.CharField(max_length=100, null=True, verbose_name='软件版本'),
        ),
    ]
