# Generated by Django 4.2.7 on 2025-09-15 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0011_alter_hardwareasset_asset_owner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='softwareasset',
            name='manufacturer',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='制造商'),
        ),
        migrations.AddField(
            model_name='softwareasset',
            name='model',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='型号'),
        ),
    ]
