# Generated by Django 4.2.7 on 2025-09-15 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0012_softwareasset_manufacturer_softwareasset_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='softwareasset',
            name='manufacturer',
        ),
        migrations.RemoveField(
            model_name='softwareasset',
            name='model',
        ),
    ]
