# Generated by Django 4.2.7 on 2025-09-15 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0013_remove_softwareasset_manufacturer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='softwareasset',
            name='warranty_status',
            field=models.CharField(choices=[('no_warranty', '原厂保'), ('limited_warranty', '第三方保'), ('unlimited_warranty', '脱保'), ('unknown', '未知')], default='unknown', max_length=40),
        ),
    ]
