# Generated by Django 4.2.7 on 2025-09-15 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0014_softwareasset_warranty_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='softwareasset',
            name='warranty_status',
        ),
    ]
