# Generated by Django 4.2.7 on 2025-09-15 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0015_remove_softwareasset_warranty_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='softwareasset',
            name='warranty_end_date',
            field=models.DateField(null=True, verbose_name='保修结束日期'),
        ),
        migrations.AddField(
            model_name='softwareasset',
            name='warranty_start_date',
            field=models.DateField(choices=[('original_warranty', '原厂保'), ('third_party_warranty', '第三方保'), ('out_of_warranty', '脱保')], null=True, verbose_name='保修开始日期'),
        ),
        migrations.AddField(
            model_name='softwareasset',
            name='warranty_type',
            field=models.CharField(choices=[('original', '原厂保修'), ('third_party', '第三方保修')], max_length=20, null=True, verbose_name='保修类型'),
        ),
    ]
