# Generated by Django 4.2.7 on 2025-09-15 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0016_softwareasset_warranty_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='softwareasset',
            name='warranty_status',
            field=models.CharField(choices=[('original_warranty', '原厂保'), ('third_party_warranty', '第三方保'), ('out_of_warranty', '脱保')], max_length=20, null=True, verbose_name='保修类型'),
        ),
        migrations.AlterField(
            model_name='softwareasset',
            name='warranty_start_date',
            field=models.DateField(null=True, verbose_name='保修开始日期'),
        ),
    ]
