# Generated by Django 4.2.7 on 2025-09-16 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0017_softwareasset_warranty_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='softwareasset',
            name='asset_status',
            field=models.CharField(choices=[('in_use', '在用')], default='in_use', max_length=20, verbose_name='资产状态'),
        ),
        migrations.AlterField(
            model_name='softwareasset',
            name='name',
            field=models.CharField(max_length=200, null=True, verbose_name='软件名称'),
        ),
    ]
