# Generated by Django 4.2.7 on 2025-09-16 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0018_alter_softwareasset_asset_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='softwareasset',
            name='specification_parameter',
            field=models.CharField(max_length=500, null=True, verbose_name='规格参数'),
        ),
        migrations.AlterField(
            model_name='softwareasset',
            name='asset_status',
            field=models.CharField(choices=[('in_use', '在用'), ('block_up', '停用')], default='in_use', max_length=20, verbose_name='资产状态'),
        ),
    ]
