# Generated by Django 4.2.7 on 2025-08-30 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='业务名称')),
                ('department', models.CharField(max_length=100, verbose_name='所属部门')),
                ('responsible_person', models.CharField(max_length=100, verbose_name='负责人')),
                ('online_date', models.DateField(verbose_name='上线日期')),
                ('access_url', models.URLField(blank=True, null=True, verbose_name='访问地址')),
                ('function_purpose', models.TextField(verbose_name='功能用途')),
                ('description', models.TextField(blank=True, null=True, verbose_name='业务描述')),
                ('status', models.CharField(choices=[('active', '运行中'), ('inactive', '已停用'), ('maintenance', '维护中'), ('testing', '测试中')], default='active', max_length=20, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '业务',
                'verbose_name_plural': '业务',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BusinessMonthlyStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='年份')),
                ('month', models.IntegerField(verbose_name='月份')),
                ('total_visits', models.BigIntegerField(default=0, verbose_name='总访问量')),
                ('unique_visitors', models.BigIntegerField(default=0, verbose_name='独立访客数')),
                ('avg_response_time', models.FloatField(default=0.0, verbose_name='平均响应时间(ms)')),
                ('uptime_percentage', models.FloatField(default=100.0, verbose_name='可用性百分比')),
                ('error_count', models.IntegerField(default=0, verbose_name='错误次数')),
                ('data_transfer_gb', models.FloatField(default=0.0, verbose_name='数据传输量(GB)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_stats', to='business.business', verbose_name='关联业务')),
            ],
            options={
                'verbose_name': '业务月度统计',
                'verbose_name_plural': '业务月度统计',
                'ordering': ['-year', '-month'],
                'unique_together': {('business', 'year', 'month')},
            },
        ),
        migrations.CreateModel(
            name='BusinessIP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(verbose_name='IP地址')),
                ('hostname', models.CharField(blank=True, max_length=200, null=True, verbose_name='主机名')),
                ('port', models.IntegerField(blank=True, null=True, verbose_name='端口')),
                ('service_type', models.CharField(choices=[('web', 'Web服务'), ('database', '数据库'), ('cache', '缓存'), ('api', 'API服务'), ('other', '其他')], default='web', max_length=50, verbose_name='服务类型')),
                ('status', models.CharField(choices=[('online', '在线'), ('offline', '离线'), ('unknown', '未知')], default='unknown', max_length=20, verbose_name='状态')),
                ('description', models.TextField(blank=True, null=True, verbose_name='描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='associated_ips', to='business.business', verbose_name='关联业务')),
            ],
            options={
                'verbose_name': '业务关联IP',
                'verbose_name_plural': '业务关联IP',
                'ordering': ['-created_at'],
                'unique_together': {('business', 'ip_address')},
            },
        ),
    ]
