# Generated by Django 4.2.7 on 2025-08-31 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='business',
            name='department',
        ),
    ]
