# Generated by Django 4.2.7 on 2025-08-31 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0002_remove_business_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='business',
            name='function_purpose',
        ),
    ]
