# Generated by Django 4.2.7 on 2025-08-31 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0003_remove_function_purpose'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='function_purpose',
            field=models.TextField(blank=True, null=True, verbose_name='功能用途'),
        ),
    ]
