# Generated by Django 4.2.7 on 2025-09-10 11:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserMenuConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collapsed_menus', models.JSONField(blank=True, default=list, help_text='存储用户折叠的菜单ID列表', verbose_name='折叠的菜单')),
                ('pinned_menus', models.JSONField(blank=True, default=list, help_text='存储用户固定的菜单ID列表', verbose_name='固定的菜单')),
                ('custom_order', models.JSONField(blank=True, default=dict, help_text='存储用户自定义的菜单排序', verbose_name='自定义排序')),
                ('theme_config', models.JSONField(blank=True, default=dict, help_text='存储用户的菜单主题配置', verbose_name='主题配置')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='menu_config', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户菜单配置',
                'verbose_name_plural': '用户菜单配置',
                'db_table': 'user_menu_config',
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='菜单名称')),
                ('title', models.CharField(max_length=100, verbose_name='显示标题')),
                ('path', models.CharField(blank=True, max_length=200, verbose_name='路由路径')),
                ('component', models.CharField(blank=True, max_length=200, verbose_name='组件路径')),
                ('icon', models.CharField(blank=True, max_length=50, verbose_name='图标')),
                ('menu_type', models.CharField(choices=[('menu', '菜单'), ('button', '按钮'), ('link', '链接')], default='menu', max_length=20, verbose_name='菜单类型')),
                ('order_num', models.IntegerField(default=0, verbose_name='排序号')),
                ('is_hidden', models.BooleanField(default=False, verbose_name='是否隐藏')),
                ('is_cache', models.BooleanField(default=True, verbose_name='是否缓存')),
                ('is_affix', models.BooleanField(default=False, verbose_name='是否固定标签')),
                ('target', models.CharField(choices=[('_self', '当前窗口'), ('_blank', '新窗口')], default='_self', max_length=10, verbose_name='打开方式')),
                ('redirect', models.CharField(blank=True, max_length=200, verbose_name='重定向路径')),
                ('permission_code', models.CharField(blank=True, help_text='关联权限编码，用于权限控制', max_length=100, verbose_name='权限编码')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='menu_management.menu', verbose_name='父菜单')),
            ],
            options={
                'verbose_name': '菜单',
                'verbose_name_plural': '菜单',
                'db_table': 'menu_management',
                'ordering': ['order_num', 'id'],
                'indexes': [models.Index(fields=['parent', 'is_active'], name='menu_manage_parent__1759d9_idx'), models.Index(fields=['order_num'], name='menu_manage_order_n_66edaf_idx'), models.Index(fields=['permission_code'], name='menu_manage_permiss_63d8b9_idx')],
            },
        ),
    ]
